[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "JetBrainsmono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsmono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsmono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsmono Nerd Font"
style = "Regular"

[scrolling]
history = 5000

[window]
opacity = 0.9

[window.class]
general = "Alacritty"
instance = "Alacritty"

[general]
live_config_reload = true

import = ["~/.config/alacritty/colorscheme.toml"]
